/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/COdesign_02.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Extrude2.geometry} material={nodes.Extrude2.material} />
      <mesh geometry={nodes.Extrude.geometry} material={materials['Mat.2']} position={[-6.6, 0.17, -0.09]} />
    </group>
  )
}

useGLTF.preload('/COdesign_02.gltf')
